---
language: python
python: "2.7"

dist: trusty
sudo: required

# Install ansible
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgis
    - postgresql-9.6-postgis-2.3
    - postgresql-9.6-postgis-2.3-scripts
    - python-pip
    - python-psycopg2

services:
  - postgresql

env:  # Content duplicated (though syntax is different here).
  - PGUSER=postgres
  - PGPASSWORD=postgres

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\npipelining=true' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.base.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.sudo.yml -i tests/inventory --syntax-check
  # Actual tests
  - ansible-playbook tests/test.sudo.yml -i tests/inventory --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
